### ISSUE TITLE
It's possible to define a element or class as a page

### ISSUE THREAD

**Issue by mmuekk** [michaelbromley/horizonal#1]
First off, I would like to congratulate you for your work.
I have a question, it's possible to define a element or class to act as a page. 

Ex: 

<div class="page">
page1
</div>

<div class="page">
page2
</div>

<div class="page">
page3
</div>

**Comment by michaelbromley** [comment]
Thank you!

Do you mean you want to have the whole pages transition all at once?

You could wrap each page in a div with a specific class, say:

``` HTML
<div class="page" id="page-1">
    <!-- your page content here -->
</div>

<div class="page" id="page-2">
    <!-- your page content here -->
</div>

<div class="page" id="page-3">
    <!-- your page content here -->
</div>
```

Style the .page class something like this:

``` CSS
.page {
   height: 100vh;
}

#page-1 {
   background-color: blue;
}
#page-2 {
   background-color: red;
}
/* etc. */
```

And then you can configure Horizonal to only select pages with a config like this:

``` JavaScript
horizonal.init({
    selector: '.page',
    pageMargin: 0
});
```
